spring:
  mvc:
    view:
      suffix: .html
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:followupDB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true